### PR TITLE
Parse pinning policy options

### LINKED ISSUE #56: Parse & display pinning policy name and properties
Speedb now ([https://github.com/speedb-io/speedb/pull/707](url)) reports to the log the pinning policy name and options / parameters. The log parser should support that similarly to block_cache / metadata_cache_options

### PR DESCRIPTION
**Pull request by udi-speedb**

### CODE REVIEW

**Comment by Yuval-Ariel** [comment]
plz add a picture of how it looks

**Comment by udi-speedb** [comment]
For the following log file:
```
  persistent_cache: (nil)
  pinning_policy_name: speedb_scoped_pinning_policy
  pinning_policy_options:
    capacity: 26843545
    last_level_with_data_percent: 10
    mid_percent: 70
  block_size: 4096
```

Screenshot from 2024-01-10 11-23-54

**Comment by udi-speedb** [comment]
Screenshot from 2024-01-10 11-27-27

**Review by Yuval-Ariel — APPROVED** [review]
great thanks

**Pull request merged**
